### ISSUE TITLE
migration issues

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa-imap-migration#11]
I have imported all the domains and user accounts into modoboa from a csv file.  I want to kick off the offline imap to sync everything up from the server I am migrating from.  It looks like the workflow you have designed for imap migration is to rely on an end user to first login to modoboa with the same username and password which as part of that process "seads" a table for offline imap to inspect and use.

Since I am loading everything up in advance (with the same username/password), is there a way to tell offline imap to just start syncing everything?

**Comment by kryskool** [comment]
Hi

To use offlineimap, you must only create domain, and after each users user the login interface in modoboa, Modoboa check if user exists in the user domain table, if not it try to connect to your old server with the login and the user password, if auth is success, Modoboa add user in the domain and add entry to the .offlineimaprc.

Modoboa assumes that we don't know the passwords of the users, and therefore each user must initiate his migration

**Comment by oconshaw** [comment]
Thanks for the clarification.  So my question, since I know the passwords of the users -- they are already predefined in modoboa through the import process -- is there a way to tell offlineimap to just sync everything up?

**Comment by tonioo** [comment]
offlineimap uses a configuration file to know the list of accounts to migrate. This list is generated by the cron script which reads the dedicated table you mentionned. Currently, if this table is empty, offlineimap won't have anything to do... When you import domains and accounts, this table is not filled.
