### ISSUE TITLE
offline imap fails

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa-imap-migration#12]
The default configuration for offline imap as generated by modoboa (.offlineimaprc) seems to require some additional details to work.  I'm not sure how it could ever work without some "tweaking" if you are using a secure connection.  I think you must reference a security certificate.

In my case, I am NOT making a secure connection to the source server.  I am using port 143, but it fails.  I think the default for offlineimap is to assume a secure connection.  I searched for a way to change this default, but couldn't find one.  To resolve this I put ssl = false and it started working.  The problem now is the .offlineimaprc file gets regenerated and overwritten from the CRON job every time this runs.

**Comment by kryskool** [comment]
Hi

in teh template i see

```
{% if imap_server_secured == "yes" %}
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
{% endif %}
```
If you don't check the secure box, it does works. can you try ?

**Comment by oconshaw** [comment]
It is NOT checked. Just verified.

**Comment by tonioo** [comment]
Looks like the default value for ``ssl`` is ``true``. I'll force it to ``false`` when the checkbox is not checked.

**Comment by Nodeswitch** [comment]
I've just installed the migration plugin, following all of the instructions details onto Modoboa 1.8.1 and I believe I'm encountering the same error. 

When attempting to log in as a user who isn't already in the database, I'm presented with the below error.

    Error: Connection to IMAP server failed: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

**Comment by tonioo** [comment]
@oconshaw why did you reopen this issue?
