### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by bystrup** [modoboa/modoboa-imap-migration#15]
In my fairly fresh install I had to change the `AUTHENTICATION_BACKENDS` to read

    AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
        'modoboa_imap_migration.auth_backends.IMAPBackend',
    )

rather than `'modoboa.lib.authbackends.SimpleBackend'` - which seems to have disappeared with revision [4c1c647](https://github.com/modoboa/modoboa/commit/4c1c64771ed569154bf59a0ab56a717f3ebf6db2#diff-14e43badd9739f4ef4bca6bd84f7cd94).

I'd be happy to create a pull request, only it seems a small fix :-)

Best regards,
Anders Bystrup

**Comment by tonioo** [comment]
@bystrup Thanks for reporting, I fixed it ;)
