### ISSUE TITLE
Problems Generate .offlineimaprc

### ISSUE THREAD

**Issue by carbans** [modoboa/modoboa-imap-migration#31]
Hi I installed Imap-migration, I configure without problems, but doesn't work. When I manually execute the script (with vmail user): 
```bash
/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py generate_offlineimap_config --output  .offlineimaprc
```
The command only generate this:
```bash
[general]
accounts = 
pythonfile = ~/.offlineimap.py
```
Is it a bug?

**Comment by tonioo** [comment]
@carbans No. It just means no user has logged in to your system yet. This plugin automatically creates a migration operation once a user from the old system logs in to Modoboa.

**Comment by carbans** [comment]
What do you mean with:

> user from the old system logs in to Modoboa

I create the domain and mailbox with the same password in modoboa. Do  I have to do something else?

**Comment by tonioo** [comment]
As indicated in the README file, you only have to configure authentication, modoboa will do the rest. And do not create accounts manually otherwise no migration will be start.
