### ISSUE TITLE
Setup fails with "No module named req"

### ISSUE THREAD

**Issue by SteJay** [modoboa/modoboa-imap-migration#33]
Here is the output I get when I try to run "python setup.py install":

root@host:/home/user/modoboa-imap-migration# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from pip.req import parse_requirements
ImportError: No module named req

From what I can tell from reading similar reports online, this is caused by using the pip.req module (as it was meant to be an internal module and its use was discouraged) being moved as of pip version 10.

I hope this information is useful to you; While I do know a little python, I have tried every fix I can think of (even using an alternate "parse_requirements" function as seen here (https://stackoverflow.com/questions/25192794/no-module-named-pip-req) but all I've managed to do is make things worse!

**Comment by tonioo** [comment]
Should be fixed now with version 1.2.1.
