### ISSUE TITLE
Can we reactivate account sync?

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-imap-migration#34]
Hello!

I've see that in admin panel -> identities we can stop sync clicking on the blue icon.

Is it possible to reactivate the sync ?

Sincerely,

**Comment by tonioo** [comment]
It is not possible for now.

**Comment by stefaweb** [comment]
To (re)activate the imap sync, the system can ask for the "old" imap server user password when we click on the icon.

**Comment by tonioo** [comment]
Don't think it is a good idea. The administrator should not know a user password, so he can't reactivate a migration. But maybe it could be done in two steps: suspend a migration (pause) or delete a migration. If suspended, a migration could be resumed since the password is still in the database.

**Comment by stefaweb** [comment]
In fact, I must explain the idea below my question.

We setup a new domain in modoboa.
We import all accounts (we don't use imap-migration as it's difficult to ask tens of users to log on the news server to activate their account).
We switch MX to the new server.
ok

But some users where using IMAP on the old server (or some new messages arrived during the mx migration).

How to manage this?

I can ask users to mount their two IMAP accounts locally and manually copy their messages but it's complicated for them.

**Comment by tonioo** [comment]
You can let the migrations active until you're sure all users have stopped using the old server?

**Comment by stefaweb** [comment]
Sorry, I may not have understood everything concerning imap-migration plug.

If the user never connect to the new server, the account do not exist.  And if the user was created using "import" imap-migration icon is not here.

**Comment by tonioo** [comment]
Ok I see. So, at some point, you'll need to know user passwords otherwise you can't automate things.
