### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by teddiey** [modoboa/modoboa-imap-migration#36]
Hi,
Tried to install this extension on a clean Modoboa Install (Ubuntu 16.04 using the modoboa installer metho) but got the following error on running **python setup.py install**:

`Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from pip._internal.req import parse_requirements
ImportError: No module named pip._internal.req`

**Comment by tonioo** [comment]
@teddiey We'll fix this issue but you can also use the regular installation way:
```shell
pip install modoboa-imap-migration
```

**Comment by demanl** [comment]
Hi, You need to add the above pip install command to your documentation for the modoboa-imap-migration page at https://github.com/modoboa/modoboa-imap-migration :)

**Comment by demanl** [comment]
Plz ignore the above msg........I just realized the instructions work just fine after I git clone this repository to my server...then cd into the newly downloaded project directory :)
