### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by cserem** [modoboa/modoboa-imap-migration#49]
Hello!

Installing and enabling the module gives internal server error for imap_migration (https://myhost/modoboa_imap_migration/), the Modoboa > Parameters page loads fine, and I am able to save settings with it.

Steps to reproduce:

Fresh install with modoboa-installer:

```
root@mail:~# ./run.py --interactive mydomain.com
root@mail:~# su - modoboa
$ bash
modoboa@mail:~$ . env/bin/activate
(env) modoboa@mail:~$ pip install modoboa-imap-migration
 modoboa@mail:~/instance/instance$ #editing the config as documented: diff settings.py settings.py.ORIG
92c92
<     'modoboa_imap_migration',
---
>
352,354d351
<
< from modoboa_imap_migration import settings as modoboa_imap_migration_settings
< modoboa_imap_migration_settings.apply(globals())
root@mail:/srv/modoboa/instance/instance# systemctl restart uwsgi

```
I have tried setting Debug = True (in settings.py), but that introduces a new error message for calendar/contacts/imap_imgration modules:
Error reading /srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_contacts/../frontend/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?" (the modoboa_xxxx module part changes with the modules)

Could you help me debug the initial internernal server error in imap_migration?

Thanks
cserem

**Comment by cserem** [comment]
- Upgrading to the latest version with
` pip install modoboa-imap-migration==1.3.2
`
makes the error dissapear, but it only shows a blank page. (The top horizontal menu is there, but the content part is just blank white)

- Reinstalling modoboa+modoboa-imap-migration from scratch yields the same

**Comment by tonioo** [comment]
@cserem Make sure you ran the collectstatic command after installation.

**Comment by cserem** [comment]
That did the trick, thanks!
