### ISSUE TITLE
only user name login without domain

### ISSUE THREAD

**Issue by cserem** [modoboa/modoboa-imap-migration#51]
Hello!

Is there a way to make the plugin work with only user names, instead of user@domain.tld logins?
On my old IMAP server the users are stored without domain names, but on the Modoboa admin panel the associated domains can not be left blank, (nor does it work with assumed special characters "*" , ".")

Thanks,
cserem

**Comment by tonioo** [comment]
@cserem Unfortunately no. Modoboa is designed for a multi-domain environment so to avoid conflicts, usernames associated to mailboxes must be regular email addresses.
