### ISSUE TITLE
Only blank page gets displayed

### ISSUE THREAD

**Issue by jamietb** [modoboa/modoboa-imap-migration#53]
I'm running Ubuntu 18.04, I made a clean install of the OS and then installed Modoboa using modoboa-installer and confirmed it was working.

I then installed the modoboa-imap-migration extension and it seemed to install fine, I followed all of the instructions and it shows up in the admin panel (Modoboa > Parameters > IMAP migration).

However my problem is when I click on IMAP Migration from the menu bar along the top it just displays a blank screen so I have no way of adding any mailboxes that I want migrated over.

Can you help me please?

**Comment by tonioo** [comment]
@jamietb Have you run the collectstatic command during the installation process?

**Comment by jamietb** [comment]
@tonioo no I haven't, I didn't see that referenced in the install documentation? I'm out at the minute but will try once I get home. Thanks.

**Comment by jamietb** [comment]
@tonioo this resolved the issue for me, thank you!
