### ISSUE TITLE
How to use migration extension

### ISSUE THREAD

**Issue by jamietb** [modoboa/modoboa-imap-migration#54]
Hey,

I'm somewhat embarrassed to post this but I really don't understand the way this extension is to be used. I think my main issue is the following:-

> A user from the old server logs into Modoboa using the same credentials

> A new account is automatically created and a new migration task is created using the provided credentials

How does a user log in if there isn't an account already created? When I try and do this my server running modoboa doesn't allow the connection.

If it helps, I'm attempting to migrate from a mailcow install to modoboa and assumed this was the best way of doing it?

Thanks,
Jamie.

**Comment by tonioo** [comment]
@jamietb The user which connects to the Modoboa web console must have an account on the old server, this is why you have to enable the IMAP authentication backend.
