### ISSUE TITLE
Everything appears installed, but configuration pages are empty:

### ISSUE THREAD

**Issue by theitmachine** [modoboa/modoboa-imap-migration#57]
-Ubuntu 18.04.3
-No errors in logs
-CronJob Runs

```
Name | Installed version | Last version | Description
-- | -- | -- | --
Modoboa | 1.14.0 | 1.14.0 | The core part of Modoboa
Amavis frontend | 1.2.3 | 1.2.3 | Simple amavis management frontend
Contacts | 0.7.3 | 0.7.3 | Address book
IMAP migration using OfflineIMAP | 1.3.3 | 1.3.3 | Migrate existing mailboxes using IMAP and OfflineIMAP
PDF credentials | 1.3.2 | 1.3.2 | Generate PDF documents containing users' credentials
Postfix autoreply | 1.5.1 | 1.5.1 | Auto-reply (vacation) functionality using Postfix
Radicale management | 1.3.6 | 1.3.6 | Management frontend for Radicale, a simple calendar and contact server.
Sieve filters | 1.4.2 | 1.4.2 | Plugin to easily create server-side filters
Statistics | 1.4.1 | 1.4.1 | Graphical statistics about emails traffic using RRDtool
Webmail | 1.5.0 | 1.5.0 | Simple IMAP webmail
```

Can't find where to enter information about old servers, either I am missing something in the setup or there's a problem.

Under the main page "Imap Migrations" tab, the resulting page is blank. View source shows no content at all.

Under ModoBoa -> Parameters -> Imap Migration
```
Current Sync Jobs 1
Create Folders Yes
Folder filter Exclusions Blank
Folder Filter Inclusions blank

Save  
```
What am I doing wrong?

**Comment by theitmachine** [comment]
Additional:
Seeing 404 errors when digging into the page source on the "IMAP Migrations" tab from the main page


```
> Failed to load resource: the server responded with a status of 404 (Not Found)
> chunk-vendors.5f40bc64.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> app.91979a7d.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> chunk-vendors.5f40bc64.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> app.91979a7d.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> app.ce08a9d0.css:1 Failed to load resource: the server responded with a status of 404 (Not Found
```

)

**Comment by tonioo** [comment]
@theitmachine Have you run the collectstatic command?

**Comment by theitmachine** [comment]
Thanks for the quick response: Here's the output of the commands to install an extension from:
https://modoboa.readthedocs.io/en/latest/installation.html

[modoboa_imap_migration.txt](https://github.com/modoboa/modoboa-imap-migration/files/3880109/modoboa_imap_migration.txt)


On the Imap Migration Tab I now get
Sorry
An internal Error Occured.


Errors on page in Source Viewer are:

Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
bootstrap-datetimepicker.min.js:1 Uncaught bootstrap-datetimepicker requires jQuery to be loaded first

**Comment by andretux** [comment]
I am getting the same errors now.  Any idea how to fix it?

**Comment by tonioo** [comment]
@andretux Can you set DEBUG to True inside settings.py, reload uwsgi and check the response tab in your browser console pleasE?

**Comment by n00dl3** [comment]
I had the same issue, and indeed, it was due to some js not being properly loaded (404 error in chrome debugger).
I had to run the `collectstatic` command :

```
cd /srv/modoboa/instance
python ./manage.py collectstatic
```
