### ISSUE TITLE
No IMAP Migration tab in Modoboa Parameters

### ISSUE THREAD

**Issue by andretux** [modoboa/modoboa-imap-migration#58]
Hallo,

I have followed the installation procedures and after initiallyfailing, because the modoboa installation uses its own instance of python, I got the environment correct (as it is in the cron tab) and tried again.  Then it worked and everything ran as expected.

Only problem is that the admin interface does not have the Modoboa > Parameters > IMAP migration tab.

I checked the config files again and restarted the webserver, but still nothing.
Any ideas why?

Thanks
Andre

**Comment by tonioo** [comment]
@andretux have you installed modoboa using the installer? If so, make sure to restart uwsgi.

**Comment by andretux** [comment]
Hi @tonioo I have just figured that out.  :-)  I was under the impression that I just had to restart nginx.

SO now I have the menu items for IMAP Migration.  Modoboa -> IMAP migration seems to work, only  options there, but the "IMAP migrations" menu item in the menu bar gives and error:
An internal error occured.

But I do not see anything in the nginx error log

**Comment by andretux** [comment]
I am getting the same errors as @theitmachine in #57 

I do not have the  /srv/modoboa/instance/sitestatic/modoboa_imap_migration folder and I get the Javascript errors:

bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
bootstrap-datetimepicker.min.js:1 Uncaught bootstrap-datetimepicker requires jQuery to be loaded first
﻿
I ran the ￼collectstatic command, but it did not make a difference

​

**Comment by el87i** [comment]
cd /user/local/lib/python3.9/dist-packages/
cp modoboa_imap_migration /srv/modoboa/env/lib/python3.9/site-packages/
cp modoboa_imap_migration-1.4.1.dist-info/ /srv/modoboa/env/lib/python3.9/site-packages/
