### ISSUE TITLE
This plugin disables modoboa's identities tab

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-imap-migration#6]
When the plugin is installed to a current modoboa revision, loading its components leads to an invalid Identities tab in modoboa.

![bildschirmfoto von 2016-07-28 20-47-44](https://cloud.githubusercontent.com/assets/1645308/17225312/bb052894-5504-11e6-8d69-9234dc8351fc.png)

**Comment by tonioo** [comment]
Could you enable the DEBUG mode (set DEBUG = True inside settings.py) and open firebug or similar to catch the error please?

**Comment by tonioo** [comment]
@almereyda any news about this?
