### ISSUE TITLE
offlineimap cronjob "NO OUTPUT GENERATED"

### ISSUE THREAD

**Issue by michalhana99** [modoboa/modoboa-imap-migration#64]
Hi,
I have problem cron job.
Modoboa IMAP migratiion dont synchronise old message.

if cron run manualy-

 Execute Cron Job
Output from command cd /srv/vmail && $PYTHON /srv/modoboa/instance/manage.py generate_offlineimap_config --output .offlineimaprc && /usr/local/bin/offlineimap > /dev/null 2>&1 ..
NO OUTPUT GENERATED

**Comment by tonioo** [comment]
@michalhana99 So you mean the .offlineimaprc file is empty?
