### ISSUE TITLE
'modoboa_imap_migration' is not a registered namespace

### ISSUE THREAD

**Issue by Cooya** [modoboa/modoboa-imap-migration#65]
I tried to migrate my mail server from my old server to my new one through the Modoboa IMAP migration plugin but I cannot make it work. I spent the whole day on it to finally be stuck upon this error :

![image](https://user-images.githubusercontent.com/22602472/86610259-613f3080-bfad-11ea-8526-f3105af7cbb2.png)

The web interface works fine if I remove the occurrences of the IMAP migration plugin in the `settings.py` file.

**Comment by harryfoster** [comment]
Just came across this myself, I believe the PyPi packaged one is lagging behind the master, in particular the commit for Django 2.2 compatibility: 7186f5db7d4970cf3482abda14f2cbdbe3c41475

I think @tonioo might have to give it a version bump on PyPi.

**Comment by surajho** [comment]
I got the same error and after reading this thread, I download the files from this repository instead of installing it with pip. But when I execute `python setup.py install` I get the following error:

`Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    INSTALL_REQUIRES = get_requirements(path.join(HERE, "requirements.txt"))
  File "setup.py", line 32, in get_requirements
    if req.match_markers():
AttributeError: 'ParsedRequirement' object has no attribute 'match_markers'`

I'm executing the command within the virtualenv on Ubuntu 20.04, Python 3.8.5 and pip 20.2.4. Has this something to do with the Python/pip versions? Or might it be something else?

**Comment by Cooya** [comment]
For information, I did not use the plugin for the migration. I ended up exporting/importing manually my emails with my email client.

**Comment by surajho** [comment]
Ok, I think I at least fixed my part. So I was able to install the plugin with the code downloaded directly from the repository. But I had to install pip 20.0.2 in order for the install to work.

**Comment by webforge** [comment]
The issue appears to be that ```modoboa_imap_migration/urls.py``` does not assign a value for ```app_name```. 

To fix, navigate to the modoboa_imap_migration directory in the instance environment (e.g.: ```/srv/modoboa/env/lib/python3.7/site-packages/modoboa_imap_migration```) and add the following line to ```urls.py``` (just after the imports and before ```urlpatterns```):

```
app_name = 'modoboa_imap_migration'
```

and then restart uwsgi:

```
sudo service uwsgi restart
```
The error should no longer appear at that point and you should also then be able to see the 'IMAP migration' tab in Admin >> Modoboa >> Parameters

**Comment by jquiros2** [comment]
> The issue appears to be that `modoboa_imap_migration/urls.py` does not assign a value for `app_name`.
> 
> To fix, navigate to the modoboa_imap_migration directory in the instance environment (e.g.: `/srv/modoboa/env/lib/python3.7/site-packages/modoboa_imap_migration`) and add the following line to `urls.py` (just after the imports and before `urlpatterns`):
> 
> ```
> app_name = 'modoboa_imap_migration'
> ```
> 
> and then restart uwsgi:
> 
> ```
> sudo service uwsgi restart
> ```
> 
> The error should no longer appear at that point and you should also then be able to see the 'IMAP migration' tab in Admin >> Modoboa >> Parameters

Wow, thank you, this is it.
