### ISSUE TITLE
OSError at /modoboa_imap_migration/

### ISSUE THREAD

**Issue by surajho** [modoboa/modoboa-imap-migration#69]
I just finished installing the plugin successfully by downloading the code from this repository. When I click on the IMAP migrations tab, I see the following error (with debug turned on):

`Error reading /srv/modoboa/env/lib/python3.8/site-packages/modoboa_imap_migration-1.3.4.dev10+g1123a58-py3.8.egg/modoboa_imap_migration/static/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?`

It does seem that the folder **static** does not exist. I followed the steps in the README and the 3 standard commands that need to be executed after every plugin installation.

Did I miss a step somewhere?

**Comment by netpanda** [comment]
Im experiencing the same issue. 

The installation seems to be going great..  no errors. 

![image](https://user-images.githubusercontent.com/11094901/105370732-c716a100-5bfb-11eb-8f0c-7ea2097f6320.png)

When I go to "IMAP Migrations" with debug on, I get the following: 

![image](https://user-images.githubusercontent.com/11094901/105371540-9e42db80-5bfc-11eb-8a9e-94bd904df07d.png)

Checking the directory, it seems that the folder: 

`/srv/modoboa/env/lib/python3.8/site-packages/modoboa_imap_migration-1.3.4.dev10+g1123a58-py3.8.egg/modoboa_imap_migration/`

Hasnt been generated.

![image](https://user-images.githubusercontent.com/11094901/105371842-ebbf4880-5bfc-11eb-8bc2-a86dab1abaae.png)

How can I force this?

**Comment by DEK4** [comment]
Hello, I have the same error.

Can some one help me to fix it? 

Thanks
