### ISSUE TITLE
How to update to latest version

### ISSUE THREAD

**Issue by louis-eyond** [modoboa/modoboa-imap-migration#84]
I have a prompt stating one or more updates is available, and listing the newest release of imap_migration:

IMAP migration using OfflineIMAP | 1.3.3 | 1.3.4 | Migrate existing mailboxes using IMAP and OfflineIMAP
-- | -- | -- | --

I've tried  _git pull origin master_, then running _python3 setup.py install_, but am not getting any update after restarting uwsgi.  It still indicates 1.3.3.  Can you provide any guidance on how to update to the latest?

**Comment by tonioo** [comment]
You need to update your package using pip:
```
su - modoboa
bash
source env/bin/active
pip install modoboa-imap-migration==1.3.4
cd instance
python manage.py migrate
python manage.py collectstatic
```
And then reload uwsgi.

**Comment by louis-eyond** [comment]
Thank you
