### ISSUE TITLE
Did usage change?

### ISSUE THREAD

**Issue by surajho** [modoboa/modoboa-imap-migration#87]
Hi,

I saw that the latest update fixed the issue I had with this module. Thank you very much for solving that. I'm making a new attempt with a fresh install of Modoboa on a Python 3 server with IMAP migration installed, and so far everything looks good.

The only thing that stomps me at the moment is how to add a account which I'd like to migrate. I used this extension already a while back, when Modoboa wasn't Python 3 compatible yet, and everything worked just as advertised after following the configuration steps in the README file.

But know, after having installed and configured everything, I keep getting the message that the username and password didn't match. Which is obvious because the account doesn't exist yet, but this also means that it is not automatically created anymore.

Also, on the IMAP migrations tab there is now also an email providers page, where I can add email providers. Is this something that I have to do? The fields I need to fill in aren't very clear.

So my questions are:

1. Is it still, install > configure > login with account you want to migrate? If so, did I miss a configuration step?
2. Am I required to add an email provider? If so, what do I need to fill in the fields?

Thank you in advance.

**Comment by tonioo** [comment]
@surajho Yes, you need to create at least one email provider which actually represents the old server you want to migrate from. Basically, it requires connection information (address, port, etc.) and one or more domains to migrate.

**Comment by surajho** [comment]
@tonioo Thanks for your reply! Alright, seems simple enough. So just to be clear on the fields:

- Name: Is just a name I give the to the provider.
- Address: Is this an IP address, and if so, does it also accept IPv6 (not necessary, but nice to know).
- Port: Seeing as I'll be importing e-mails, I assume this is a IMAP(S) or POP3 port, correct?

**Comment by tonioo** [comment]
@surajho my answers:

- Name: yes
- Address: yes it's an IP address but I've never tried with ipv6
- Port: IMAP only (so 143 or 993)

**Comment by surajho** [comment]
@tonioo Thanks!
